language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pdeziel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pdeziel/docker-react npm run test